application: {{ $.AppName }}
version: 1
runtime: go
api_version: go1

nobuild_files:
- vendor
- gopath/vendor

skip_files:
- vendor/.*$
- gopath/vendor/.*$

handlers:
- url: /.*
  script: _go_app

- url: /favicon\.ico
  static_files: assets/favicon.ico
  upload: web/favicon\.ico
  expiration: "14d"
 
